2022/08/24 09:47:41 [error] [php] date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. (/Users/sagi/repos/WebApp/protected/views/layouts/main.php:51)
Stack trace:
#0 /Users/sagi/repos/WebApp/protected/views/layouts/main.php(51): date()
#1 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CBaseController.php(126): require()
#2 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CBaseController.php(95): SiteController->renderInternal()
#3 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/widgets/CContentDecorator.php(76): SiteController->renderFile()
#4 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/widgets/CContentDecorator.php(54): CContentDecorator->decorate()
#5 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/widgets/COutputProcessor.php(44): CContentDecorator->processOutput()
#6 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CBaseController.php(215): CContentDecorator->run()
#7 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CBaseController.php(309): SiteController->endWidget()
#8 /Users/sagi/repos/WebApp/protected/views/layouts/column1.php(6): SiteController->endContent()
#9 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CBaseController.php(126): require()
#10 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CBaseController.php(95): SiteController->renderInternal()
#11 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CController.php(787): SiteController->renderFile()
#12 /Users/sagi/repos/WebApp/protected/controllers/SiteController.php(32): SiteController->render()
#13 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): SiteController->actionIndex()
#14 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams()
#15 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CController.php(286): SiteController->runAction()
#16 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CController.php(265): SiteController->runActionWithFilters()
#17 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): SiteController->run()
#18 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController()
#19 /Users/sagi/repos/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#20 /Users/sagi/repos/WebApp/index.php(13): CWebApplication->run()
REQUEST_URI=/
in /Users/sagi/repos/WebApp/protected/views/layouts/main.php (51)
in /Users/sagi/repos/WebApp/protected/views/layouts/column1.php (6)
in /Users/sagi/repos/WebApp/protected/controllers/SiteController.php (32)
2022/08/24 09:48:43 [error] [php] date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. (/Users/sagi/repos/WebApp/protected/views/layouts/main.php:51)
Stack trace:
#0 /Users/sagi/repos/WebApp/protected/views/layouts/main.php(51): date()
#1 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CBaseController.php(126): require()
#2 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CBaseController.php(95): SiteController->renderInternal()
#3 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/widgets/CContentDecorator.php(76): SiteController->renderFile()
#4 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/widgets/CContentDecorator.php(54): CContentDecorator->decorate()
#5 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/widgets/COutputProcessor.php(44): CContentDecorator->processOutput()
#6 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CBaseController.php(215): CContentDecorator->run()
#7 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CBaseController.php(309): SiteController->endWidget()
#8 /Users/sagi/repos/WebApp/protected/views/layouts/column1.php(6): SiteController->endContent()
#9 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CBaseController.php(126): require()
#10 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CBaseController.php(95): SiteController->renderInternal()
#11 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CController.php(787): SiteController->renderFile()
#12 /Users/sagi/repos/WebApp/protected/controllers/SiteController.php(32): SiteController->render()
#13 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): SiteController->actionIndex()
#14 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams()
#15 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CController.php(286): SiteController->runAction()
#16 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CController.php(265): SiteController->runActionWithFilters()
#17 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): SiteController->run()
#18 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController()
#19 /Users/sagi/repos/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#20 /Users/sagi/repos/WebApp/index.php(13): CWebApplication->run()
REQUEST_URI=/inde
in /Users/sagi/repos/WebApp/protected/views/layouts/main.php (51)
in /Users/sagi/repos/WebApp/protected/views/layouts/column1.php (6)
in /Users/sagi/repos/WebApp/protected/controllers/SiteController.php (32)
2022/08/24 09:48:49 [error] [php] date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. (/Users/sagi/repos/WebApp/protected/views/layouts/main.php:51)
Stack trace:
#0 /Users/sagi/repos/WebApp/protected/views/layouts/main.php(51): date()
#1 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CBaseController.php(126): require()
#2 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CBaseController.php(95): SiteController->renderInternal()
#3 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/widgets/CContentDecorator.php(76): SiteController->renderFile()
#4 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/widgets/CContentDecorator.php(54): CContentDecorator->decorate()
#5 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/widgets/COutputProcessor.php(44): CContentDecorator->processOutput()
#6 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CBaseController.php(215): CContentDecorator->run()
#7 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CBaseController.php(309): SiteController->endWidget()
#8 /Users/sagi/repos/WebApp/protected/views/layouts/column1.php(6): SiteController->endContent()
#9 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CBaseController.php(126): require()
#10 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CBaseController.php(95): SiteController->renderInternal()
#11 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CController.php(787): SiteController->renderFile()
#12 /Users/sagi/repos/WebApp/protected/controllers/SiteController.php(32): SiteController->render()
#13 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): SiteController->actionIndex()
#14 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams()
#15 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CController.php(286): SiteController->runAction()
#16 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CController.php(265): SiteController->runActionWithFilters()
#17 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): SiteController->run()
#18 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController()
#19 /Users/sagi/repos/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#20 /Users/sagi/repos/WebApp/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php
in /Users/sagi/repos/WebApp/protected/views/layouts/main.php (51)
in /Users/sagi/repos/WebApp/protected/views/layouts/column1.php (6)
in /Users/sagi/repos/WebApp/protected/controllers/SiteController.php (32)
2022/08/24 13:39:03 [error] [exception.CException] exception 'CException' with message 'm220824_103633_create_book_table and its behaviors do not have a method or closure named "primaryKey".' in /Users/sagi/repos/yii-1.1.25.43e386/framework/base/CComponent.php:266
Stack trace:
#0 /Users/sagi/repos/WebApp/protected/migrations/m220824_103633_create_book_table.php(8): CComponent->__call('primaryKey', Array)
#1 /Users/sagi/repos/WebApp/protected/migrations/m220824_103633_create_book_table.php(8): m220824_103633_create_book_table->primaryKey()
#2 /Users/sagi/repos/yii-1.1.25.43e386/framework/cli/commands/MigrateCommand.php(415): m220824_103633_create_book_table->up()
#3 /Users/sagi/repos/yii-1.1.25.43e386/framework/cli/commands/MigrateCommand.php(109): MigrateCommand->migrateUp('m220824_103633_...')
#4 [internal function]: MigrateCommand->actionUp(Array)
#5 /Users/sagi/repos/yii-1.1.25.43e386/framework/console/CConsoleCommand.php(178): ReflectionMethod->invokeArgs(Object(MigrateCommand), Array)
#6 /Users/sagi/repos/yii-1.1.25.43e386/framework/console/CConsoleCommandRunner.php(71): CConsoleCommand->run(Array)
#7 /Users/sagi/repos/yii-1.1.25.43e386/framework/console/CConsoleApplication.php(92): CConsoleCommandRunner->run(Array)
#8 /Users/sagi/repos/yii-1.1.25.43e386/framework/base/CApplication.php(185): CConsoleApplication->processRequest()
#9 /Users/sagi/repos/yii-1.1.25.43e386/framework/yiic.php(33): CApplication->run()
#10 /Users/sagi/repos/WebApp/protected/yiic.php(7): require_once('/Users/sagi/rep...')
#11 /Users/sagi/repos/WebApp/protected/yiic(4): require_once('/Users/sagi/rep...')
#12 {main}
---
2022/08/24 13:56:59 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CWebApplication.php:286
Stack trace:
#0 /Users/sagi/repos/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#1 /Users/sagi/repos/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#2 /Users/sagi/repos/WebApp/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=gii
---
2022/09/05 12:11:46 [error] [php] date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. (/Users/sagi/repos/source/SharePosts/protected/views/layouts/main.php:51)
Stack trace:
#0 /Users/sagi/repos/source/SharePosts/protected/views/layouts/main.php(51): date()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CBaseController.php(126): require()
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CBaseController.php(95): SiteController->renderInternal()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/widgets/CContentDecorator.php(76): SiteController->renderFile()
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/widgets/CContentDecorator.php(54): CContentDecorator->decorate()
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/widgets/COutputProcessor.php(44): CContentDecorator->processOutput()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CBaseController.php(215): CContentDecorator->run()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CBaseController.php(309): SiteController->endWidget()
#8 /Users/sagi/repos/source/SharePosts/protected/views/layouts/column1.php(6): SiteController->endContent()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CBaseController.php(126): require()
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CBaseController.php(95): SiteController->renderInternal()
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(787): SiteController->renderFile()
#12 /Users/sagi/repos/source/SharePosts/protected/controllers/SiteController.php(32): SiteController->render()
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): SiteController->actionIndex()
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams()
#15 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): SiteController->runAction()
#16 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): SiteController->runActionWithFilters()
#17 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): SiteController->run()
#18 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController()
#19 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#20 /Users/sagi/repos/source/SharePosts/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/index
in /Users/sagi/repos/source/SharePosts/protected/views/layouts/main.php (51)
in /Users/sagi/repos/source/SharePosts/protected/views/layouts/column1.php (6)
in /Users/sagi/repos/source/SharePosts/protected/controllers/SiteController.php (32)
2022/09/05 12:11:50 [error] [php] date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. (/Users/sagi/repos/source/SharePosts/protected/views/layouts/main.php:51)
Stack trace:
#0 /Users/sagi/repos/source/SharePosts/protected/views/layouts/main.php(51): date()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CBaseController.php(126): require()
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CBaseController.php(95): SiteController->renderInternal()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/widgets/CContentDecorator.php(76): SiteController->renderFile()
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/widgets/CContentDecorator.php(54): CContentDecorator->decorate()
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/widgets/COutputProcessor.php(44): CContentDecorator->processOutput()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CBaseController.php(215): CContentDecorator->run()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CBaseController.php(309): SiteController->endWidget()
#8 /Users/sagi/repos/source/SharePosts/protected/views/layouts/column1.php(6): SiteController->endContent()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CBaseController.php(126): require()
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CBaseController.php(95): SiteController->renderInternal()
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(787): SiteController->renderFile()
#12 /Users/sagi/repos/source/SharePosts/protected/controllers/SiteController.php(32): SiteController->render()
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): SiteController->actionIndex()
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams()
#15 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): SiteController->runAction()
#16 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): SiteController->runActionWithFilters()
#17 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): SiteController->run()
#18 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController()
#19 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#20 /Users/sagi/repos/source/SharePosts/index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/index
in /Users/sagi/repos/source/SharePosts/protected/views/layouts/main.php (51)
in /Users/sagi/repos/source/SharePosts/protected/views/layouts/column1.php (6)
in /Users/sagi/repos/source/SharePosts/protected/controllers/SiteController.php (32)
2022/09/06 10:48:44 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] Server sent charset unknown to the client. Please, report to the developers' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/default/index
---
2022/09/06 10:50:23 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] Server sent charset unknown to the client. Please, report to the developers' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/default/index
---
2022/09/06 10:50:25 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] Server sent charset unknown to the client. Please, report to the developers' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/default/index
---
2022/09/06 10:50:25 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] Server sent charset unknown to the client. Please, report to the developers' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/default/index
---
2022/09/06 10:50:25 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] Server sent charset unknown to the client. Please, report to the developers' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/default/index
---
2022/09/06 10:50:43 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] Server sent charset unknown to the client. Please, report to the developers' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/default/index
---
2022/09/06 10:50:44 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] Server sent charset unknown to the client. Please, report to the developers' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/default/index
---
2022/09/06 10:51:00 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] Server sent charset unknown to the client. Please, report to the developers' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/crud/CrudCode.php(44): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): CrudCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/crud/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/crud/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/controller/index
---
2022/09/06 10:51:16 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] Server sent charset unknown to the client. Please, report to the developers' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/form/index
---
2022/09/06 10:52:24 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] Server sent charset unknown to the client. Please, report to the developers' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/form/index
---
2022/09/06 10:53:11 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] Server sent charset unknown to the client. Please, report to the developers' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/form/index
---
2022/09/06 10:53:12 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] Server sent charset unknown to the client. Please, report to the developers' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/form/index
---
2022/09/06 10:57:56 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] Server sent charset unknown to the client. Please, report to the developers' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/form/index
---
2022/09/06 10:57:57 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] Server sent charset unknown to the client. Please, report to the developers' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/form/index
---
2022/09/06 10:58:16 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] Server sent charset unknown to the client. Please, report to the developers' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/form/index
---
2022/09/06 10:58:17 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] Server sent charset unknown to the client. Please, report to the developers' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/form/index
---
2022/09/06 11:03:37 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/form/index
---
2022/09/06 11:03:44 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/form/index
---
2022/09/06 11:03:53 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/form/index
---
2022/09/06 11:03:53 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/form/index
---
2022/09/06 11:03:54 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/form/index
---
2022/09/06 11:04:07 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/form/index
---
2022/09/06 11:04:50 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/form/index
---
2022/09/06 11:05:39 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/form/index
---
2022/09/06 11:05:40 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/form/index
---
2022/09/06 11:05:40 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/form/index
---
2022/09/06 11:05:40 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/form/index
---
2022/09/06 11:05:40 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/form/index
---
2022/09/06 11:05:40 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/form/index
---
2022/09/06 11:05:41 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/form/index
---
2022/09/06 11:05:41 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/form/index
---
2022/09/06 11:05:41 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/form/index
---
2022/09/06 11:05:41 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/form/index
---
2022/09/06 11:05:41 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/form/index
---
2022/09/06 11:05:52 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/form/index
---
2022/09/06 11:05:52 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/form/index
---
2022/09/06 11:05:53 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/form/index
---
2022/09/06 11:05:53 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client' in /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php:399
Stack trace:
#0 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(347): CDbConnection->open()
#1 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/db/CDbConnection.php(325): CDbConnection->setActive(true)
#2 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(394): CDbConnection->init()
#3 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CModule.php(103): CModule->getComponent('db')
#4 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/generators/model/ModelCode.php(60): CModule->__get('db')
#5 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CFormModel.php(39): ModelCode->init()
#6 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(153): CFormModel->__construct()
#7 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/gii/CCodeGenerator.php(63): CCodeGenerator->prepare()
#8 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/actions/CInlineAction.php(49): CCodeGenerator->actionIndex()
#9 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#10 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(282): CController->run('index')
#13 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/model/index')
#14 /Users/sagi/repos/source/yii-1.1.25.43e386/framework/base/CApplication.php(185): CWebApplication->processRequest()
#15 /Users/sagi/repos/source/SharePosts/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php?r=gii/model/index
HTTP_REFERER=http://localhost:8000/index.php?r=gii/form/index
---
2022/09/06 11:12:51 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'shareposts.tbl_users' doesn't exist. The SQL statement executed was: SHOW FULL COLUMNS FROM `tbl_users`.
in /Users/sagi/repos/source/SharePosts/index.php (13)
